@TodoAPI_HostAddress = https://localhost:7081

POST {{TodoAPI_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}
###

GET {{TodoAPI_HostAddress}}/todoitems

###

GET {{TodoAPI_HostAddress}}/todoitems/1

###
