// <auto-generated />
using System;
using API.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 12, 21, 54, 28, 276, DateTimeKind.Local).AddTicks(6994),
                            FirstName = "Jordan",
                            LastName = "Davila",
                            UpdatedAt = new DateTime(2024, 1, 12, 21, 54, 28, 276, DateTimeKind.Local).AddTicks(7049)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 12, 21, 54, 28, 276, DateTimeKind.Local).AddTicks(7056),
                            FirstName = "Giovanni",
                            LastName = "Krueger",
                            UpdatedAt = new DateTime(2024, 1, 12, 21, 54, 28, 276, DateTimeKind.Local).AddTicks(7058)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 12, 21, 54, 28, 276, DateTimeKind.Local).AddTicks(7062),
                            FirstName = "Marjorie",
                            LastName = "Nolan",
                            UpdatedAt = new DateTime(2024, 1, 12, 21, 54, 28, 276, DateTimeKind.Local).AddTicks(7064)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
